name: Build

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    paths-ignore: ['*.md']
    branches: ['master']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: start9labs/shared-workflows/.github/workflows/build.yml@master
    # with:
    #   FREE_DISK_SPACE: true